SELECT
   [TrusteeAlias]
  , [TrusteePrimarySMTPAddress]
  , [TrusteeRecipientTypeDetails]
  , [TargetAlias]
  , [TargetPrimarySMTPAddress]
  , [TargetRecipientTypeDetails]
  , [PermissionType]
  , [FolderAccessRights]
  , [TargetFolderType]
  , [TrusteeIdentity]
  , [TrusteeExchangeGUID]
  , [TargetExchangeGUID]
  , [TrusteeDistinguishedName]
  , [TargetDistinguishedName]
FROM
    [dbo].[viewPermissionsReport]