SELECT
      [WhenListChangedUTC]
      ,[Change]
      ,[Alias]
      ,[Name]
      ,[DisplayName]
      ,[PrimarySmtpAddress]
      ,[ExchangeGuid]
      ,[AssignedWave]
      ,[WaveAssignmentSource]
      ,[RecipientTypeDetails]
      ,[TargetAddress]
      ,[OrganizationalUnit]
      ,[WhenCreatedUTC]

  FROM [dbo].[viewMostRecentMigrationListChanges]
