-- Deletes the records that are in the updat but not others, preserving old records, if any
DELETE stagingWorkday
--select * FROM stagingWorkday
WHERE EmployeeID IN (SELECT EmployeeID FROM stagingWorkdayUpdate)
GO
-- adds the replacement and new records back in
INSERT INTO [dbo].[stagingWorkday]
           ([EmployeeID]
           ,[Worker]
           ,[EmailAddress]
           ,[EmployeeType]
           ,[TimeType]
           ,[FTEPercent]
           ,[WorkerType]
           ,[ContingentWorkerType]
           ,[JobTitle]
           ,[JobProfile]
           ,[JobCategory]
           ,[ManagementLevel]
           ,[Manages]
           ,[DirectReportCount]
           ,[HireDate]
           ,[TermDate]
           ,[ContingentContractEndDate]
           ,[EndEmploymentDate]
           ,[ContinuousServiceDate]
           ,[Location]
           ,[HasAltPrimaryEmail]
           ,[LocationCountry]
           ,[Company]
           ,[BusinessUnit]
           ,[Division]
           ,[Region]
           ,[JobFamily]
           ,[JobFamilyGroup]
           ,[CostCenter]
           ,[Manager]
           ,[ManagerEmail]
           ,[LeaveStatus])
SELECT 
      [EmployeeID]
      ,[Worker]
      ,[EmailAddress]
      ,[EmployeeType]
      ,[TimeType]
      ,[FTEPercent]
      ,[WorkerType]
      ,[ContingentWorkerType]
      ,[JobTitle]
      ,[JobProfile]
      ,[JobCategory]
      ,[ManagementLevel]
      ,[Manages]
      ,[DirectReportCount]
      ,[HireDate]
      ,[TerminationDate]
      ,[ContingentContractEndDate]
      ,[EndEmploymentDate]
      ,[ContinuousServiceDate]
      ,[Location]
      ,[HasAltPrimaryEmail]
      ,[LocationCountry]
      ,[Company]
      ,[BusinessUnit]
      ,[Division]
      ,[Region]
      ,[JobFamily]
      ,[JobFamilyGroup]
      ,[CostCenter]
      ,[Manager]
      ,[ManagerEmail]
	  ,[EmploymentStatus] LeaveStatus
  FROM [dbo].[stagingWorkdayUpdate]
WHERE EmployeeID NOT IN (SELECT EmployeeID from stagingWorkday)
