SELECT TOP (1000) N.[AzureADSync]
      ,N.[AssignedWave]
      ,N.[IsVIP]
      ,N.[Domain]
      ,N.[LinkedDomain]
      ,N.[ExchangeOrg]
      ,N.[SamAccountName]
      ,N.[DisplayName]
      ,N.[mailnickname]
      ,N.[Mail]
      ,N.[LinkedMail]
      ,N.[PrimarySmtpAddress]
      ,N.[UserPrincipalName]
      ,N.[UPNMatchesSMTP]
      ,N.[Company]
      ,N.[Department]
      ,N.[ObjectGUID]
      ,N.[LinkedObjectGUID]
      ,N.[OWAEnabled]
      ,N.[CitrixOutlook]
      ,N.[OtherMailboxAccess]
      ,N.[LitigationHoldEnabled]
      ,N.[DIV_DESC]
      ,N.[COST_CTR_DESC]
      ,N.[BUS_AREA]
      ,N.[COST_CTR]
      ,N.[DIV_CODE]
      ,N.[RecipientTypeDetails]

  FROM [Migration].[dbo].[MigrationList] N

  WHERE N.AssignedWave = '3.2'