MERGE dbo.AADUsers AS Target USING [dbo].[IncomingAADUsers] AS Source ON (Target.ObjectId = Source.ObjectID)
WHEN MATCHED THEN
UPDATE
SET
    DeletionTimestamp = Source.DeletionTimestamp,
    ObjectType = Source.ObjectType,
    AccountEnabled = Source.AccountEnabled,
    City = Source.City,
    CompanyName = Source.CompanyName,
    Country = Source.Country,
    CreationType = Source.CreationType,
    Department = Source.Department,
    DirSyncEnabled = Source.DirSyncEnabled,
    DisplayName = Source.DisplayName,
    FacsimileTelephoneNumber = Source.FacsimileTelephoneNumber,
    GivenName = Source.GivenName,
    IsCompromised = Source.IsCompromised,
    ImmutableId = Source.ImmutableId,
    JobTitle = Source.JobTitle,
    LastDirSyncTime = Source.LastDirSyncTime,
    Mail = Source.Mail,
    MailNickName = Source.MailNickName,
    Mobile = Source.Mobile,
    OnPremisesSecurityIdentifier = Source.OnPremisesSecurityIdentifier,
    OtherMails = Source.OtherMails,
    PasswordPolicies = Source.PasswordPolicies,
    PasswordProfile = Source.PasswordProfile,
    PhysicalDeliveryOfficeName = Source.PhysicalDeliveryOfficeName,
    PostalCode = Source.PostalCode,
    PreferredLanguage = Source.PreferredLanguage,
    ProvisioningErrors = Source.ProvisioningErrors,
    ProxyAddresses = Source.ProxyAddresses,
    RefreshTokensValidFromDateTime = Source.RefreshTokensValidFromDateTime,
    ShowInAddressList = Source.ShowInAddressList,
    SignInNames = Source.SignInNames,
    SipProxyAddress = Source.SipProxyAddress,
    [State] = Source.State,
    StreetAddress = Source.StreetAddress,
    Surname = Source.Surname,
    TelephoneNumber = Source.TelephoneNumber,
    UsageLocation = Source.UsageLocation,
    UserPrincipalName = Source.UserPrincipalName,
    UserState = Source.UserState,
    UserStateChangedOn = Source.UserStateChangedOn,
    UserType = Source.UserType
    WHEN NOT MATCHED BY TARGET THEN
INSERT
    (
        DeletionTimestamp,
        ObjectId,
        ObjectType,
        AccountEnabled,
        City,
        CompanyName,
        Country,
        CreationType,
        Department,
        DirSyncEnabled,
        DisplayName,
        FacsimileTelephoneNumber,
        GivenName,
        IsCompromised,
        ImmutableId,
        JobTitle,
        LastDirSyncTime,
        Mail,
        MailNickName,
        Mobile,
        OnPremisesSecurityIdentifier,
        OtherMails,
        PasswordPolicies,
        PasswordProfile,
        PhysicalDeliveryOfficeName,
        PostalCode,
        PreferredLanguage,
        ProvisioningErrors,
        ProxyAddresses,
        RefreshTokensValidFromDateTime,
        ShowInAddressList,
        SignInNames,
        SipProxyAddress,
        State,
        StreetAddress,
        Surname,
        TelephoneNumber,
        UsageLocation,
        UserPrincipalName,
        UserState,
        UserStateChangedOn,
        UserType
    )
VALUES
    (
        Source.DeletionTimestamp,
        Source.ObjectId,
        Source.ObjectType,
        Source.AccountEnabled,
        Source.City,
        Source.CompanyName,
        Source.Country,
        Source.CreationType,
        Source.Department,
        Source.DirSyncEnabled,
        Source.DisplayName,
        Source.FacsimileTelephoneNumber,
        Source.GivenName,
        Source.IsCompromised,
        Source.ImmutableId,
        Source.JobTitle,
        Source.LastDirSyncTime,
        Source.Mail,
        Source.MailNickName,
        Source.Mobile,
        Source.OnPremisesSecurityIdentifier,
        Source.OtherMails,
        Source.PasswordPolicies,
        Source.PasswordProfile,
        Source.PhysicalDeliveryOfficeName,
        Source.PostalCode,
        Source.PreferredLanguage,
        Source.ProvisioningErrors,
        Source.ProxyAddresses,
        Source.RefreshTokensValidFromDateTime,
        Source.ShowInAddressList,
        Source.SignInNames,
        Source.SipProxyAddress,
        Source.State,
        Source.StreetAddress,
        Source.Surname,
        Source.TelephoneNumber,
        Source.UsageLocation,
        Source.UserPrincipalName,
        Source.UserState,
        Source.UserStateChangedOn,
        Source.UserType
    )
    WHEN NOT MATCHED BY SOURCE THEN DELETE
    OUTPUT $action,
    DELETED.ObjectID AS DELETEDTargetObjectID,
    DELETED.UserPrincipalName AS DELETEDTargetUserPrincipalName,
    DELETED.OnPremisesSecurityIdentifier AS DELETEDTargetOPObjectSID,
    INSERTED.ObjectID AS INSERTEDTargetObjectID,
    INSERTED.UserPrincipalName AS INSERTEDTargetUserPrincipalName,
    INSERTED.OnPremisesSecurityIdentifier AS INSERTEDTargetOPObjectSID;